# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sttr < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.1.0/sttr_0.1.0_macOS-64bit.tar.gz"
      sha256 "852b384bd339562b15408ec93a97400a71a0a56259f7cefe9c250997ac915613"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.1.0/sttr_0.1.0_linux-64bit.tar.gz"
      sha256 "e9d014cf9ee1b074ce8e50770c93de36caa6ee2b82b300a384e8870a18a69959"
    end
  end

  def install
    bin.install "sttr"
  end
end
