# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sttr < Formula
  desc "A cross-platform, cli app to perform various string operations."
  homepage "https://github.com/abhimanyu003/sttr"
  version "0.2.30"
  license "MIT"

  on_macos do
    url "https://github.com/abhimanyu003/sttr/releases/download/v0.2.30/sttr_Darwin_all.tar.gz"
    sha256 "91dd8a96e7b7a89761bbbf455d22b5ad409f8e068bfe23e3dd78be42ec671512"

    def install
      bin.install "sttr"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.2.30/sttr_Linux_x86_64.tar.gz"
      sha256 "f4cb5b240853b53f67d7b789c9cf5969e794675c5c38aad2ed5ff2c065be4c19"
      def install
        bin.install "sttr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.2.30/sttr_Linux_arm64.tar.gz"
      sha256 "3653d0b1ebebae7cc93e96260d03a872698e3bc689f3162de31c758f25331311"
      def install
        bin.install "sttr"
      end
    end
  end

  test do
    system "#{bin}/sttr -v"
  end
end
