# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sttr < Formula
  desc "A cross-platform, cli app to perform various string operations."
  homepage "https://github.com/abhimanyu003/sttr"
  version "0.2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.2.9/sttr_0.2.9_darwin_amd64.tar.gz"
      sha256 "e0f4a0767a583fd9e543ce044bafed763b9473564d929163c0c82251810fb81d"

      def install
        bin.install "sttr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/sttr/releases/download/v0.2.9/sttr_0.2.9_linux_amd64.tar.gz"
      sha256 "ff8da284b17e0507cbecab195112d9c0cfae2d2500384baf0289e4c1aea23ee1"

      def install
        bin.install "sttr"
      end
    end
  end

  test do
    system "#{bin}/sttr -v"
  end
end
